name: Build

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

        golang_version: [1.22.5]
        java_version: ['21']
        python_version: ['3.8', '3.10', '3.12']
        rust_version: [stable]

    env:
      OS: ${{ matrix.os }}

      GOLANG_VERSION: ${{ matrix.golang_version }}
      JAVA_VERSION: ${{ matrix.java_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      RUST_VERSION: ${{ matrix.rust_version }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}
        components: rustfmt
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java_version }}
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.golang_version }}
    - name: Install Python dependencies
      run: pip install codecov tox tox-gh-actions
    - name: Run Tox
      run: tox
    - name: Upload coverage to Codecov
      if: ${{ success() }}
      uses: codecov/codecov-action@v4
      with:
        env_vars: OS,GOLANG_VERSION,JAVA_VERSION,OS,PYTHON_VERSION,RUST_VERSION

  precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: pip install tox
    - name: Run Tox
      run: tox -e pre-commit
